camel:
  springboot:
    # The Camel context name
    name: CamelActiveMQ
    main-run-controller: true

# Binding health checks to a different port
#management:
  port: 8081

# disable all management endpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

  

logging:
  config: classpath:logback.xml


# The name of the service hosting the ActiveMQ broker or message gateway
# Can be customized using the 'ACTIVEMQ_SERVICE_NAME' variable to use a different broker.
activemq:
  service:
    name: activemq
# The following properties can be customized using the 'ACTIVEMQ_SERVICE_HOST' and 'ACTIVEMQ_SERVICE_PORT' environment variables.
# This is indeed done automatically by Kubernetes when the application is deployed in a namespace containing an instance of ActiveMQ named 'activemq'.
# The service defaults to localhost. You need to change these properties for development purposes only.
    host: localhost
  broker: 
    username: admin
    password: admin
    
# The following property binds all previous configurations together
    url: vm://${${activemq.service.name}.service.host}?broker.persistent=false
  concurrent: 
    consumers: 10
  pool: 
     max:
      connections: 8

# email configuration
# user name : user email
# password : user email password


mail.from: 
mail.smtp.host: smtp.gmail.com
mail.port: 587
mail.user: 
mail.passsword: 

mail.tls: true 
ssl.trust: true   
mail.smtp.auth: true
mail.ssl.trust: smtp.gmail.com

 

